#:schema https://raw.githubusercontent.com/cloudflare/workers-sdk/main/packages/wrangler/config-schema.json
name = "starball"
compatibility_date = "2024-04-01"

[pages]
functions_directory = "" # Explicitly disable functions to prevent the publish error
